package View;

import daoImpl.CategoriaDaoImpl;
import daoImpl.ColorDaoImpl;
import daoImpl.ContieneDaoImpl;
import daoImpl.MarcaDaoImpl;
import daoImpl.ProductoDaoImpl;
import daoImpl.TallaDaoImpl;
import daoImpl.VendidoDaoImpl;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import model.DetalleVenta;
import model.Nodo;


public class JimVendido extends javax.swing.JInternalFrame {
    private VendidoDaoImpl crudVendido;
    private DefaultTableModel modelo;
    private Object[] filaDatos;
    private ProductoDaoImpl IDaoProducto;
    private CategoriaDaoImpl IDaoCategoria;
    private MarcaDaoImpl IDaoMarca;
    private TallaDaoImpl IDaoTalla;
    private ColorDaoImpl IDaoColor;
    private ContieneDaoImpl IDaoContiene;
    
    public JimVendido() {
        initComponents();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setSize(ancho, alto-106);
        crudVendido = new VendidoDaoImpl();
        modelo = new DefaultTableModel();
        filaDatos = new Object[8];
        IDaoProducto = new ProductoDaoImpl();
        IDaoCategoria = new CategoriaDaoImpl();
        IDaoMarca = new MarcaDaoImpl();
        IDaoTalla = new TallaDaoImpl();
        IDaoColor = new ColorDaoImpl();
        IDaoContiene = new ContieneDaoImpl();
        listarProductosVendidos();
    }
    
    private void listarProductosVendidos() {
        modelo = (DefaultTableModel) tblProductosVendidos.getModel();
        for (DetalleVenta devent : crudVendido.listar()) {
            if (devent != null ) {
                Nodo aux = IDaoContiene.inicio;
                while (aux != null) {
                    if (aux.getContiene().getIdContiene() == devent.getIdProducto()) {
                        filaDatos[0] = devent.getIdProducto();
                        filaDatos[1] = IDaoProducto.obtenerNombre(aux.getContiene().getIdProducto());
                        filaDatos[2] = IDaoCategoria.obtenerNombre(IDaoProducto.obtenerCategoria(aux.getContiene().getIdProducto()));
                        filaDatos[3] = IDaoMarca.obtenerNombre(aux.getContiene().getIdMarca());
                        filaDatos[4] = IDaoTalla.obtenerNombre(aux.getContiene().getIdTalla());
                        filaDatos[5] = IDaoColor.obtenerNombre(aux.getContiene().getIdColor());
                        filaDatos[6] = devent.getPrecio();
                        filaDatos[7] = devent.getCantidad();
                        modelo.addRow(filaDatos);
                    }
                    aux = aux.siguiente;
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductosVendidos = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Productos más Vendidos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        tblProductosVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoría", "Marca", "Talla", "Color", "Precio", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(tblProductosVendidos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1120, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProductosVendidos;
    // End of variables declaration//GEN-END:variables
}
